name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v0.0.1, v0.0.2, etc.

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Generate Release Notes
      run: |
        python PythonScripts/generate_release_notes.py ${{ github.ref_name }}

    - name: Commit and Push Release Notes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Add release notes for ${{ github.ref_name }}"
        branch: main  # Make sure this matches your target branch

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
